apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: nginx-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: nginx-web-server
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-web-server
  labels:
    app: nginx-web-server
spec:
  selector:
    matchLabels:
      app: nginx-web-server
  template:
    metadata:
      labels:
        app: nginx-web-server
    spec:
      volumes:
        - name: nginx-storage
          persistentVolumeClaim:
            claimName: nginx-claim
      containers:
        - name: task-pv-container
          image: nginx
          livenessProbe:
            httpGet:
              path: /healthy
              port: 80
            initialDelaySeconds: 15
            timeoutSeconds: 1
            periodSeconds: 120
            failureThreshold: 3
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: "http-server"
          volumeMounts:
            - mountPath: "/usr/share/nginx/html"
              name: nginx-storage