apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-nfs
  labels:
    volume: nginx-volume
spec:
  accessModes:
  - ReadOnlyMany
  capacity:
    storage: 5Gi
  nfs:
    server: k8smaster.local
    path: "/home/pi/nfsshare/nginx"