apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-nfs
  labels:
    volume: mysql-volume
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  nfs:
    server: k8smaster.local
    path: "/home/pi/nfsshare/mysql"