apiVersion: v1
kind: PersistentVolume
metadata:
  name: jupyter-nfs
  labels:
    volume: jupyter-volume
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 5Gi
  nfs:
    server: k8smaster.local
    path: "/home/pi/nfsshare/notebooks"