kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jupyter-claim
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      volume: jupyter-volume