apiVersion: v1
kind: Service
metadata:
  name: led-controller
  labels:
    app: led-controller
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: led-controller
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: led-controller
  labels:
   app: led-controller
spec:
  replicas: 2
  selector:
    matchLabels:
      app: led-controller
  template:
    metadata:
      labels:
        app: led-controller
    spec:
      # ensure of pods on different nodes
      # https://kubernetes.io/docs/concepts/configuration/assign-pod-node/
      affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: led-controller
                  operator: In
                  values:
                  - led-controller
              topologyKey: "kubernetes.io/hostname"
    spec:
      containers:
      - name: led-controller
        image: glovebox/led-controller:arm32v7-0.6
        imagePullPolicy: Always
        securityContext:
          privileged: true
        ports:
        - containerPort: 80
          protocol: TCP