apiVersion: v1
kind: Service
metadata:
  name: led-controller
  labels:
    app: led-controller
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: led-controller
---
apiVersion: v1
kind: Pod
metadata:
  name: led-controller
  labels:
    app: led-controller
spec:
  containers:
  - name: led-controller
    image: glovebox/led-python:0.5.1-arm32v7
    ports:
    - containerPort: 80
    securityContext:
      privileged: true
  nodeSelector:
    kubernetes.io/hostname: k8snode2 
    # https://kubernetes.io/docs/concepts/configuration/assign-pod-node/
    # kubectl label nodes k8snode2 name=k8snode2  
    # kubectl label nodes k8snode1 name=k8snode1