apiVersion: v1
kind: Service
metadata:
  name: kuard
  labels:
    app: kuard
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: kuard
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: kuard
  labels:
   app: kuard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kuard
  template:
    metadata:
      labels:
        app: kuard
    spec:
      volumes:
      - name: "kuard-data"
        persistentVolumeClaim:
            claimName: "kuard-claim"
      containers:
      - name: kuard
        # https://github.com/kubernetes-up-and-running/kuard
        image: gcr.io/kuar-demo/kuard-arm:blue
        volumeMounts:
          - mountPath: "/data"
            name: "kuard-data"
        livenessProbe:
          httpGet:
            path: /healthy
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 10
          failureThreshold: 3
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP

