kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: kuard-claim
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      volume: kuard-volume